"""
FROZEN AS BASELINE (Phase 3, section 7): this is Blocking V1. Do not modify —
it is the baseline that V2 (ml/candidate_generation/blocking_v2.py) is
measured against. Any improvement work happens in blocking_v2.py, not here.

ReconLens — candidate generation (blocking), V1.

Never compares every ledger record against every settlement record. Blocks
on amount proximity + date window, which are the two dimensions Phase 1's
corruption model bounds tightly (settlement lag capped at 5 days; amount
drift capped at a few percent or a small flat fee) — so a correct match can
never legitimately fall outside a reasonably generous window, and anything
outside it is a real candidate to exclude, not a risk of losing recall.

This module explicitly reports its own recall against the hidden match map
in a SEPARATE evaluation step (not here — see docs/candidate_generation_eval.md
generated by scripts/evaluate_candidate_recall.py) so that "did blocking lose
a legitimate match" is measured, not assumed away.
"""

from __future__ import annotations

import pandas as pd

AMOUNT_WINDOW_RATIO = 0.05      # ledger amount +/- 5% covers fee deductions and drift
AMOUNT_WINDOW_FLOOR = 50.0      # minimum absolute window, for small transactions
DATE_WINDOW_DAYS = 7            # generous vs. the generator's 5-day settlement lag cap


def generate_candidates(ledger_df: pd.DataFrame, settlement_df: pd.DataFrame) -> list[tuple[str, str]]:
    """Returns list of (ledger_id, settlement_id) candidate pairs.

    Batched settlements (sum of several ledger amounts) will legitimately
    fall OUTSIDE a single-record amount window — this is a known, documented
    limitation of amount-window blocking, not a bug: recovering many-to-one
    batches requires a separate combinatorial-sum search, which is out of
    scope for Phase 2 blocking and is flagged here rather than silently
    producing false confidence in candidate-generation recall.
    """
    settlement_df = settlement_df.copy()
    settlement_df["txn_date_parsed"] = pd.to_datetime(settlement_df["txn_date"])
    ledger_df = ledger_df.copy()
    ledger_df["txn_date_parsed"] = pd.to_datetime(ledger_df["txn_date"])

    # Sort settlement by date for a coarse windowed scan rather than a full
    # cross join — keeps this well clear of true O(n*m) even at larger scale.
    settlement_df = settlement_df.sort_values("txn_date_parsed").reset_index(drop=True)

    pairs = []
    for _, led in ledger_df.iterrows():
        window = max(led["amount"] * AMOUNT_WINDOW_RATIO, AMOUNT_WINDOW_FLOOR)
        lo, hi = led["amount"] - window, led["amount"] + window
        date_lo = led["txn_date_parsed"] - pd.Timedelta(days=0)  # settlement is never before the txn
        date_hi = led["txn_date_parsed"] + pd.Timedelta(days=DATE_WINDOW_DAYS)

        candidates = settlement_df[
            (settlement_df["amount"] >= lo) & (settlement_df["amount"] <= hi) &
            (settlement_df["txn_date_parsed"] >= date_lo) & (settlement_df["txn_date_parsed"] <= date_hi)
        ]
        for _, stl in candidates.iterrows():
            pairs.append((led["ledger_id"], stl["settlement_id"]))

    return pairs
