"""initial schema

Revision ID: b8fdedb0fbb5
Revises: 
Create Date: 2026-08-28 09:17:47.947780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fdedb0fbb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('batch_hash', sa.String(), nullable=False),
    sa.Column('n_ledger_records', sa.Integer(), nullable=True),
    sa.Column('n_settlement_records', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_hash'), 'batches', ['batch_hash'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('ledger_record_ids', sa.JSON(), nullable=False),
    sa.Column('settlement_record_ids', sa.JSON(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('high_threshold', sa.Float(), nullable=False),
    sa.Column('low_threshold', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('workflow_state', sa.String(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_batch_id'), 'decisions', ['batch_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_batch_id'), 'source_records', ['batch_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('evidence_direction', sa.String(), nullable=False),
    sa.Column('evidence_strength', sa.String(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_decision_id'), 'evidence_records', ['decision_id'], unique=False)
    op.create_table('exception_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_records_decision_id'), 'exception_records', ['decision_id'], unique=True)
    op.create_table('review_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('assigned_reviewer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_decision_id'), 'review_tasks', ['decision_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_tasks_decision_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_exception_records_decision_id'), table_name='exception_records')
    op.drop_table('exception_records')
    op.drop_index(op.f('ix_evidence_records_decision_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_source_records_batch_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_decisions_batch_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_batches_batch_hash'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
